/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingStatusRouteImport } from './routes/booking-status'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuthenticatedRouteRouteImport } from './routes/admin/_authenticated/route'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthenticatedDashboardRouteImport } from './routes/admin/_authenticated/dashboard'
import { Route as AdminAuthenticatedReceptionRouteImport } from './routes/admin/_authenticated/reception'
import { Route as AdminAuthenticatedRoomsRouteImport } from './routes/admin/_authenticated/rooms'
import { Route as AdminAuthenticatedSettingsRouteImport } from './routes/admin/_authenticated/settings'
import { Route as AdminAuthenticatedStaffRouteImport } from './routes/admin/_authenticated/staff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingStatusRoute = BookingStatusRouteImport.update({
  id: '/booking-status',
  path: '/booking-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedRouteRoute = AdminAuthenticatedRouteRouteImport.update({
  id: '/admin/_authenticated',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedDashboardRoute =
  AdminAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedReceptionRoute =
  AdminAuthenticatedReceptionRouteImport.update({
    id: '/reception',
    path: '/reception',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedRoomsRoute = AdminAuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminAuthenticatedRouteRoute,
} as any)
const AdminAuthenticatedSettingsRoute =
  AdminAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedStaffRoute = AdminAuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminAuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-status': typeof BookingStatusRoute
  '/admin': typeof AdminAuthenticatedRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard': typeof AdminAuthenticatedDashboardRoute
  '/admin/reception': typeof AdminAuthenticatedReceptionRoute
  '/admin/rooms': typeof AdminAuthenticatedRoomsRoute
  '/admin/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/staff': typeof AdminAuthenticatedStaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-status': typeof BookingStatusRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard': typeof AdminAuthenticatedDashboardRoute
  '/admin/reception': typeof AdminAuthenticatedReceptionRoute
  '/admin/rooms': typeof AdminAuthenticatedRoomsRoute
  '/admin/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/staff': typeof AdminAuthenticatedStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-status': typeof BookingStatusRoute
  '/admin/_authenticated': typeof AdminAuthenticatedRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_authenticated/dashboard': typeof AdminAuthenticatedDashboardRoute
  '/admin/_authenticated/reception': typeof AdminAuthenticatedReceptionRoute
  '/admin/_authenticated/rooms': typeof AdminAuthenticatedRoomsRoute
  '/admin/_authenticated/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/_authenticated/staff': typeof AdminAuthenticatedStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-status'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/admin/dashboard'
    | '/admin/reception'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-status'
    | '/admin'
    | '/admin/login'
    | '/admin/dashboard'
    | '/admin/reception'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/staff'
  id:
    | '__root__'
    | '/'
    | '/booking-status'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/admin/'
    | '/admin/_authenticated/dashboard'
    | '/admin/_authenticated/reception'
    | '/admin/_authenticated/rooms'
    | '/admin/_authenticated/settings'
    | '/admin/_authenticated/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingStatusRoute: typeof BookingStatusRoute
  AdminAuthenticatedRouteRoute: typeof AdminAuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-status': {
      id: '/booking-status'
      path: '/booking-status'
      fullPath: '/booking-status'
      preLoaderRoute: typeof BookingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/dashboard': {
      id: '/admin/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthenticatedDashboardRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/reception': {
      id: '/admin/_authenticated/reception'
      path: '/reception'
      fullPath: '/admin/reception'
      preLoaderRoute: typeof AdminAuthenticatedReceptionRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/rooms': {
      id: '/admin/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminAuthenticatedRoomsRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/settings': {
      id: '/admin/_authenticated/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthenticatedSettingsRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/staff': {
      id: '/admin/_authenticated/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminAuthenticatedStaffRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
  }
}

interface AdminAuthenticatedRouteRouteChildren {
  AdminAuthenticatedDashboardRoute: typeof AdminAuthenticatedDashboardRoute
  AdminAuthenticatedReceptionRoute: typeof AdminAuthenticatedReceptionRoute
  AdminAuthenticatedRoomsRoute: typeof AdminAuthenticatedRoomsRoute
  AdminAuthenticatedSettingsRoute: typeof AdminAuthenticatedSettingsRoute
  AdminAuthenticatedStaffRoute: typeof AdminAuthenticatedStaffRoute
}

const AdminAuthenticatedRouteRouteChildren: AdminAuthenticatedRouteRouteChildren =
  {
    AdminAuthenticatedDashboardRoute: AdminAuthenticatedDashboardRoute,
    AdminAuthenticatedReceptionRoute: AdminAuthenticatedReceptionRoute,
    AdminAuthenticatedRoomsRoute: AdminAuthenticatedRoomsRoute,
    AdminAuthenticatedSettingsRoute: AdminAuthenticatedSettingsRoute,
    AdminAuthenticatedStaffRoute: AdminAuthenticatedStaffRoute,
  }

const AdminAuthenticatedRouteRouteWithChildren =
  AdminAuthenticatedRouteRoute._addFileChildren(
    AdminAuthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingStatusRoute: BookingStatusRoute,
  AdminAuthenticatedRouteRoute: AdminAuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
